### ISSUE TITLE
Canon camera intermittently reports 'busy' on LCD & won't take photos

### ISSUE THREAD

**Issue by greiginsydney** [greiginsydney/Intervalometerator#123]
Some models of Canon camera may manifest an intermittent issue where the camera's LCD display reports "busy", and the camera won't take a photo.

Unplugging the USB cable restores the ability to take photos.

<p align="center">
<img src="https://user-images.githubusercontent.com/11004787/185728776-3ed640ed-f55c-479a-af22-1bc9113a0017.png" width="60%">
 </p>

This appears to be a bug in the version of libgphoto (one of the underlying components) that's installed with the "bullseye" version of Raspberry Pi o/s. [[Ref#1](https://github.com/gphoto/libgphoto2/issues/352)] [[Ref#2](https://github.com/gphoto/gphoto2/issues/465)]

Intvlm8r's still running on the earlier "buster" o/s are not affected.

### How to tell if you're at risk

From the "System Maintenance" page, check the `Pi o/s version` and `libgphoto2 version`:

<p align="center">
<img src="https://user-images.githubusercontent.com/11004787/185729027-15152c14-48f4-466c-8eb9-a35e2224eaa6.png" width="60%">
 </p>

__libgphoto2 version 2.5.27 is the problem.__

### Resolution

An update to the `setup.sh` script is currently being soak-tested. If it detects a "legacy" installation of libgphoto2 it will first uninstall it and then install the latest version directly from GitHub.

An upside to this change is that newer camera models will be supported by the intvlm8r sooner than would have otherwise been the case.

<br>

\- Greig.

**Comment by wj7106** [comment]
Last year, I reflected on this problem. Maybe the description was not very clear at that time, https://github.com/greiginsydney/Intervalometerator/issues/80

**Comment by greiginsydney** [comment]
Nah, that was a different scenario. In this case all USB-related comms is fine: you can take and view a Preview image and view/change all other camera parameters, however the on-camera 'shoot' button is inoperative, as is the remote trigger input.

**Comment by greiginsydney** [comment]
Fixed in Release v4.5.0.
