### ISSUE TITLE
Camera time not updating from the web interface

### ISSUE THREAD

**Issue by aerialvideographyuk** [greiginsydney/Intervalometerator#139]
Just put a test camera up for a future project.
While setting the time from the web interface for pi, arduino and camera, the camera doesn't set and goes to 2000 Jan 01 00:00:00
Further attemps at just setting the camera only results in the same issue.

**Comment by greiginsydney** [comment]
Hi Dave,

<br>

"Alt camera time mode" should fix that:

<br>

![image](https://github.com/greiginsydney/Intervalometerator/assets/11004787/c5ab8937-7052-4d61-b949-e2a0c2cbbac0)

Let me know if not and hopefully we can work together on a better fix.

<br>

\- G.

**Comment by greiginsydney** [comment]
Hey @aerialvideographyuk have you had any luck with that?

**Comment by greiginsydney** [comment]
I've created a new FAQ to help anyone encountering this issue in the future:
-  [Why cant I set the camera's time correctly](https://github.com/greiginsydney/Intervalometerator/blob/master/docs/FAQ.md#Why-cant-I-set-the-cameras-time-correctly)
