### ISSUE TITLE
4.6.0 version cannot change camera parameters

### ISSUE THREAD

**Issue by wj7106** [greiginsydney/Intervalometerator#150]
I don't know if everyone has installed and run version 4.6.0. I can't change camera parameters on the camera page, but there was an error when confirming!

Browser display:

Bad Request
The browser (or proxy) sent a request that this server could not understand.

**Comment by greiginsydney** [comment]
Whoops. Yes that's definitely a bug.

I should be able to get 4.6.1 out later today to fix that. 

Thanks for bringing it to my attention.
