### ISSUE TITLE
4.6.2   FTP

### ISSUE THREAD

**Issue by wj7106** [greiginsydney/Intervalometerator#157]
There seems to be an issue with the latest FTP function in 4.6.2,
Log display
2024/03/11 12:17:27
2024/03/11 12:17:27 OK to transfer @ 12:00 Method=FTP
2024/03/11 12:17:27 Status: Commercing upload using FTP
The page encountered a transmission error, but there was no error message in the log,
I will go back to 4.5.5 and use the universal FTP server address and username password to use it

**Comment by greiginsydney** [comment]
What was the next line in the log after "commencing upload"?

If an error message is received I log it, but of course if it fails silently I have nothing to log.

Is this a reproducible issue, or a one-off?
