### ISSUE TITLE
Add "Delete all images" function

### ISSUE THREAD

**Issue by OzRocky** [greiginsydney/Intervalometerator#17]
If someone is using a small memory card and retrieving the images on a regular basis, or maybe automatically uploading them somewhere, they may find they are running out of space on the memory card in the camera and/or the Pi. As a last resort, they will need to delete all the images after they have downloaded them.

Because this is so dangerous, you need to confirm the intention by some foolproof mechanism. Like "Please enter the phrase _'Yes I know what I'm doing and I really want to delete these images forever.'_ in the box below to confirm. Or maybe something slightly shorter. 

Deleting the images from the camera and the Pi should be done separately.

**Comment by greiginsydney** [comment]
There are two ways to address this. The first is to enable the "deleteAfter..." options in the INI file. That's referenced in [this FAQ article](https://github.com/greiginsydney/Intervalometerator/blob/master/docs/FAQ.md#my-camera-andor-pi-are-running-low-on-storage-how-can-i-delete-old-images).

To delete EVERYTHING off the camera, there's an example script in jim's python-gphoto2 folder that will do that for you. I've referenced it (and given an example) in Issue #91 

\- G.
