### ISSUE TITLE
piTransfer google oauth registration fails with syntax error.

### ISSUE THREAD

**Issue by peterjbaylis** [greiginsydney/Intervalometerator#55]
Hi Greig;
Thanks for publishing the Intervalometerator project.
Building and testing the project so far has been a voyage of discovery, I still have a few kinks to iron out in the bench testing phase.
I want to setup my google drive to receive images from the intvlm8r, so I followed the setup upload options instructions.
I have the json file from the Google API in my /home/pi/www folder.
When I run the piTransfer.py script it exits with a syntax error.

See screenshot included.
![pi_cap_03](https://user-images.githubusercontent.com/3692941/93768620-d212f200-fc58-11ea-95bb-1cb91f3f7b6a.PNG)

Any suggestions to resolve this would be appreciated.
Regards Peter.

**Comment by greiginsydney** [comment]
Hi Peter,


Ooh, I don't know how that got there; my apologies.

The "else" test on line 472 should have a colon after it.

I've just fixed it in the ['bugfixes-2009' branch](/greiginsydney/intervalometerator/tree/bugfixes-2009).

Please let me know if you encounter any more issues.

\- G.
