### ISSUE TITLE
Add telemetry / health monitoring

### ISSUE THREAD

**Issue by greiginsydney** [greiginsydney/Intervalometerator#8]
Add some Azure IoT-style telemetry, so you can remotely monitor it. Generate an alarm if it stops taking photos or fails to report in.

**Comment by cadpix** [comment]
This would be very useful, our Intvlm8r is running on solar in a remote location to see a building go up over two years. We have it working over 4G and we can access the UI (via remote.it) and it can upload the pics to dropbox which works well. 
It would be great to be able monitor the system / battery voltage and set a low threshold warning so we can anticipate a 12v battery replacement if needed.
Our setup also utilises a PTC heater to defrost the front glass. This only draws around an amp and clears the frost in winter, being able to see some temp data would be useful for anticipating when to kick this in or maybe this could be switched on by the RPI in the future? We currently use a digital timer switch to switch the heat on but this would be a fantastic feature addition to the Intvlm8r.

**Comment by aerialvideographyuk** [comment]
I am also trying to get things working over a 4g wifi dongle and over traditional wifi but without port forwarding.  I removed the fixed ip settings on the pi and installed remote.it on the pi.  I could then set up a connection for ssh, http on port 80 and https on port 443. everything appeared to be working fine as I was able to access the camera via remote.it and change settings etc.  However I then noticed that no photo's were getting transferred to dropbox. When I checked the photos have stayed on the camera and not gone to the pi.  attached are the cameraTransfer.log and the gunicorn.error files. Any help appreaciated.
[cameraTransfer.log.txt](https://github.com/greiginsydney/Intervalometerator/files/6274373/cameraTransfer.log.txt)
[gunicorn.error.txt](https://github.com/greiginsydney/Intervalometerator/files/6274375/gunicorn.error.txt)

**Comment by greiginsydney** [comment]
Resolved with the addition of 'heartbeating' in release 4.2.0.

**Comment by techydude** [comment]
Hey @cadpix , a few questions to clarify:
 
> It would be great to be able monitor the system / battery voltage and set a low threshold warning so we can anticipate a 12v battery replacement if needed.

(q1) are you saying you setup a system with a battery, no other forms of power input, and need to periodically go to site and replace the battery?  If so, have you had any (supre-system / offboard) means of ascertaining battery state-of-charge, or do you just work out after some time how long the battery lasts and adjust your site visit rate?

> Our setup also utilises a PTC heater (common in security cameras and cheap too!) to defrost the front glass on the housing. This only draws around an amp and clears the frost in winter, being able to see some temp data would be useful for anticipating when to kick this in or maybe this could be switched on by the RPI in the future? We currently use a digital timer switch to switch the heat on but this would be a fantastic feature addition to the Intvlm8r.

(q2) 1 Amp * battery voltage (whatever that is, let's say a 12V SLA) is 12 Watts, which is an awful lot.  Do you have some way to only turn this front glass heater on just (a few minutes?) before a shot's about to be taken?  Or do you leave it on permanently when the weather's cold? (which suggests you need an effing big battery in winter! lol)

(q3) temp sensing:  do you want to know the tempeature inside the box, or outside the box, or both?  (I think Greig's add in a internal temp sensor telemetry in recent released, long after you posted your comment) in terms of estimating the need to apply a heater to the glass, I suspect you'd need to know both temps, and perhaps the humidity inside the box too, to work out how close you are to the dew temp, right?
