### ISSUE TITLE
 Canon 650's fault has been removed 

### ISSUE THREAD

**Issue by wj7106** [greiginsydney/Intervalometerator#81]
I have reinstalled Python gPhoto2 once. The preview can not be automatically standby now. It is ready to use!
Libgphoto2 is the latest version of 2.5.27!

pi@raspberrypi:/usr/local/share/python-gphoto2/examples $ python3 gphoto2_version.py
python: 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0]
libgphoto2: ['2.5.27', 'standard camlib set SKIPPING SOME (ax203 canon digigr8 dimagev directory docupen jl2005a jl2005c kodak_dc240 mars pentax ptp2 ricoh_g3 sierra sonix sq905 st2205 topfield tp6801 SKIPPING lumix)', 'gcc (C compiler used)', 'ltdl (for portable loading of camlibs)', 'EXIF (for special handling of EXIF files)']
python-gphoto2: 2.3.0

**Comment by greiginsydney** [comment]
That's great news. I'll leave the code in the new release anyway, but remove the entry for the 650D.

Thanks for letting me know.
